###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'

    mariadb:
        image: 'mariadb:11.0'
        working_dir: /src
        volumes:
            - '.:/src'
        environment:
            - MYSQL_ROOT_PASSWORD=admin123
            - MYSQL_DATABASE=teste
            - MYSQL_USER=admin_teste
            - MYSQL_PASSWORD=admin123
        ports:
            - '33003:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /src
        volumes:
            - '.:/src'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '33000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /src
        volumes:
            - '.:/src'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
